// Code generated by gint-gen. DO NOT EDIT.
// source: user.gint

package types

// CreateUserReq CreateUser 请求
type CreateUserReq struct {
	Name  string `json:"name" validate:"required"`
	Email string `json:"email" validate:"required,email"`
}

// CreateUserResp CreateUser 响应
type CreateUserResp struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

// GetUserResp GetUser 响应
type GetUserResp struct {
	Id    int64  `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

// ListUsersReq ListUsers 请求
type ListUsersReq struct {
	Page int `json:"page"`
	Size int `json:"size"`
}

// ListUsersResp ListUsers 响应
type ListUsersResp struct {
	Total int           `json:"total"`
	Items []GetUserResp `json:"items"`
}
