// Copyright 2025 ink-yht-code
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"bufio"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/ink-yht-code/gint/gint-gen/generator"
	"github.com/ink-yht-code/gint/gint-gen/parser"
	"github.com/spf13/cobra"
)

// getModuleNameFromGoMod 从当前目录的 go.mod 获取模块名
func getModuleNameFromGoMod() string {
	data, err := os.ReadFile("go.mod")
	if err != nil {
		return ""
	}
	scanner := bufio.NewScanner(strings.NewReader(string(data)))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(line, "module ") {
			return strings.TrimPrefix(line, "module ")
		}
	}
	return ""
}

var apiCmd = &cobra.Command{
	Use:   "api <name>",
	Short: "从 .gint 文件生成 HTTP 代码",
	Long: `从 .gint 文件生成 types/handler/routes。

示例:
  gint-gen api user                  # 解析 user/user.gint
  gint-gen api user --file my.gint   # 指定文件`,
	Args: cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		name := args[0]
		file, _ := cmd.Flags().GetString("file")
		if file == "" {
			// Prefer ./<name>.gint when invoked inside the service dir.
			candidate := name + ".gint"
			if _, err := os.Stat(candidate); err == nil {
				file = candidate
			} else if err != nil && !isNotExist(err) {
				fmt.Fprintf(os.Stderr, "Error: %v\n", err)
				os.Exit(1)
			} else {
				file = filepath.Join(name, name+".gint")
			}
		}

		if err := genAPI(name, file); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("API code generated for '%s'.\n", name)
	},
}

func isNotExist(err error) bool {
	if err == nil {
		return false
	}
	return errors.Is(err, fs.ErrNotExist)
}

func init() {
	rootCmd.AddCommand(apiCmd)
	apiCmd.Flags().StringP("file", "f", "", ".gint 文件路径")
}

func genAPI(name, file string) error {
	// 解析 .gint 文件
	p := parser.NewParser()
	api, err := p.ParseFile(file)
	if err != nil {
		return fmt.Errorf("parse .gint file: %w", err)
	}

	if err := api.Validate(); err != nil {
		return err
	}

	// 生成 types.go
	if err := genTypes(name, api); err != nil {
		return err
	}

	// 生成 handler_gen.go（可覆盖） & handler_impl.go（仅首次创建）
	if err := genHandlerGen(name, api); err != nil {
		return err
	}
	if err := genHandlers(name, api); err != nil {
		return err
	}

	// 生成 routes.go
	if err := genRoutes(name, api); err != nil {
		return err
	}

	return nil
}

func genTypes(name string, api *parser.API) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by gint-gen. DO NOT EDIT.\n")
	buf.WriteString("// source: " + name + ".gint\n\n")
	buf.WriteString("package types\n\n")

	for _, t := range api.Types {
		buf.WriteString(fmt.Sprintf("// %s %s\n", t.Name, t.Name))
		buf.WriteString(fmt.Sprintf("type %s struct {\n", t.Name))
		for _, f := range t.Fields {
			goType := parser.GoType(f.Type)
			tag := f.Tag
			if tag != "" {
				// 自动添加 form tag 如果只有 json tag
				if strings.Contains(tag, `json:`) && !strings.Contains(tag, `form:`) {
					// 提取 json tag 值
					jsonRe := regexp.MustCompile(`json:"([^"]+)"`)
					jsonMatches := jsonRe.FindStringSubmatch(tag)
					if len(jsonMatches) > 1 {
						tag = tag + ` form:"` + jsonMatches[1] + `"`
					}
				}
				buf.WriteString(fmt.Sprintf("\t%s %s `%s`\n", f.Name, goType, tag))
			} else {
				buf.WriteString(fmt.Sprintf("\t%s %s\n", f.Name, goType))
			}
		}
		buf.WriteString("}\n\n")
	}

	// 检查是否在服务目录内（存在 internal/types 目录）
	typesPath := "internal/types/types_gen.go"
	if _, err := os.Stat("internal/types"); os.IsNotExist(err) {
		// 不在服务目录内，使用 name 前缀
		typesPath = filepath.Join(name, "internal", "types", "types_gen.go")
	}

	return generator.GenerateFileForce(typesPath, buf.String())
}

func genHandlerGen(name string, api *parser.API) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by gint-gen. DO NOT EDIT.\n")
	buf.WriteString("// source: " + name + ".gint\n\n")
	buf.WriteString("package web\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/gin-gonic/gin\"\n")
	buf.WriteString("\t\"github.com/ink-yht-code/gint/gint\"\n")
	buf.WriteString("\t\"" + name + "/internal/service\"\n")
	buf.WriteString(")\n\n")

	// Handler struct
	buf.WriteString("// Handler HTTP 处理器\n")
	buf.WriteString("// 实现 gint.Handler 接口\n")
	buf.WriteString("type Handler struct {\n")
	buf.WriteString("\tsvc *service." + strings.Title(name) + "Service\n")
	buf.WriteString("}\n\n")

	// NewHandler
	buf.WriteString("// NewHandler 创建 Handler\n")
	buf.WriteString("func NewHandler(svc *service." + strings.Title(name) + "Service) *Handler {\n")
	buf.WriteString("\treturn &Handler{svc: svc}\n")
	buf.WriteString("}\n\n")

	// PrivateRoutes
	buf.WriteString("// PrivateRoutes 注册需要认证的路由\n")
	buf.WriteString("func (h *Handler) PrivateRoutes(server *gin.Engine) {\n")
	buf.WriteString("\t// TODO: 你可以在这里挂载鉴权中间件\n")
	for _, svc := range api.Services {
		prefix := svc.Prefix
		if prefix == "" {
			prefix = ""
		}
		for _, route := range svc.Routes {
			if !route.Private {
				continue
			}
			fullPath := strings.TrimRight(prefix, "/") + route.Path
			if prefix == "" {
				fullPath = route.Path
			}
			if route.Request != "" {
				buf.WriteString(fmt.Sprintf("\tserver.%s(\"%s\", gint.B(h.%s))\n",
					route.Method, fullPath, route.Handler))
			} else {
				buf.WriteString(fmt.Sprintf("\tserver.%s(\"%s\", gint.W(h.%s))\n",
					route.Method, fullPath, route.Handler))
			}
		}
	}
	buf.WriteString("}\n\n")

	// PublicRoutes
	buf.WriteString("// PublicRoutes 注册公开的路由\n")
	buf.WriteString("func (h *Handler) PublicRoutes(server *gin.Engine) {\n")
	for _, svc := range api.Services {
		prefix := svc.Prefix
		if prefix == "" {
			prefix = ""
		}
		for _, route := range svc.Routes {
			if route.Private {
				continue
			}
			fullPath := strings.TrimRight(prefix, "/") + route.Path
			if prefix == "" {
				fullPath = route.Path
			}
			if route.Request != "" {
				buf.WriteString(fmt.Sprintf("\tserver.%s(\"%s\", gint.B(h.%s))\n",
					route.Method, fullPath, route.Handler))
			} else {
				buf.WriteString(fmt.Sprintf("\tserver.%s(\"%s\", gint.W(h.%s))\n",
					route.Method, fullPath, route.Handler))
			}
		}
	}
	buf.WriteString("}\n\n")
	buf.WriteString("// Health 健康检查\n")
	buf.WriteString("func (h *Handler) Health(c *gin.Context) {\n")
	buf.WriteString("\tc.JSON(200, gin.H{\"status\": \"ok\"})\n")
	buf.WriteString("}\n")

	// 检查是否在服务目录内
	handlerPath := "internal/web/handler_gen.go"
	if _, err := os.Stat("internal/web"); os.IsNotExist(err) {
		handlerPath = filepath.Join(name, "internal", "web", "handler_gen.go")
	}

	return generator.GenerateFileForce(handlerPath, buf.String())
}

func genHandlers(name string, api *parser.API) error {
	// 每个 service 一个 handlers 文件：<service>_handlers.go
	for _, svc := range api.Services {
		if err := genServiceHandlersFile(name, svc); err != nil {
			return err
		}
	}
	return nil
}

func genServiceHandlersFile(moduleName string, svc parser.Service) error {
	// 检查是否在服务目录内
	fileName := filepath.Join("internal", "web", strings.ToLower(svc.Name)+"_handlers.go")
	inServiceDir := true
	if _, err := os.Stat("internal/web"); os.IsNotExist(err) {
		fileName = filepath.Join(moduleName, "internal", "web", strings.ToLower(svc.Name)+"_handlers.go")
		inServiceDir = false
	}

	// 如果在服务目录内，从 go.mod 获取模块名
	if inServiceDir {
		if modName := getModuleNameFromGoMod(); modName != "" {
			moduleName = modName
		}
	}

	// read existing methods (incremental append)
	existing := make(map[string]struct{})
	if b, err := os.ReadFile(fileName); err == nil {
		existing = extractHandlerMethods(string(b))
	}

	var buf strings.Builder
	if _, err := os.Stat(fileName); err == nil {
		// file exists: append missing stubs at end
		buf.WriteString("\n")
		for _, r := range svc.Routes {
			if _, ok := existing[r.Handler]; ok {
				continue
			}
			genHandlerMethodStub(&buf, r)
		}
		if buf.Len() == 0 {
			return nil
		}
		f, err := os.OpenFile(fileName, os.O_APPEND|os.O_WRONLY, 0644)
		if err != nil {
			return err
		}
		defer f.Close()
		_, err = f.WriteString(buf.String())
		return err
	}

	// create new file
	buf.WriteString("package web\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/ink-yht-code/gint/gint\"\n")
	buf.WriteString("\t\"github.com/ink-yht-code/gint/gint/gctx\"\n")
	buf.WriteString("\t\"" + moduleName + "/internal/service\"\n")
	buf.WriteString("\t\"" + moduleName + "/internal/types\"\n")
	buf.WriteString(")\n\n")

	for _, r := range svc.Routes {
		genHandlerMethodStub(&buf, r)
	}

	return generator.GenerateFile(fileName, buf.String())
}

func extractHandlerMethods(src string) map[string]struct{} {
	res := make(map[string]struct{})
	// func (h *Handler) MethodName(
	re := regexp.MustCompile(`func\s*\(h\s*\*Handler\)\s*([A-Za-z_][A-Za-z0-9_]*)\s*\(`)
	matches := re.FindAllStringSubmatch(src, -1)
	for _, m := range matches {
		if len(m) > 1 {
			res[m[1]] = struct{}{}
		}
	}
	return res
}

func genHandlerMethodStub(buf *strings.Builder, route parser.Route) {
	buf.WriteString("func (h *Handler) " + route.Handler + "(")
	if route.Request != "" {
		buf.WriteString("ctx *gctx.Context, req *types." + route.Request)
	} else {
		buf.WriteString("ctx *gctx.Context")
	}
	buf.WriteString(") (gint.Result, error) {\n")
	buf.WriteString("\treturn gint.Result{Code: 0}, nil\n")
	buf.WriteString("}\n\n")
}

func genRoutes(name string, api *parser.API) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by gint-gen. DO NOT EDIT.\n")
	buf.WriteString("// source: " + name + ".gint\n\n")
	buf.WriteString("package web\n\n")
	buf.WriteString("import \"github.com/gin-gonic/gin\"\n\n")

	for _, svc := range api.Services {
		buf.WriteString(fmt.Sprintf("// Register%sRoutes 注册 %s 服务路由\n", strings.Title(svc.Name), svc.Name))
		buf.WriteString(fmt.Sprintf("func Register%sRoutes(r *gin.Engine, h *Handler) {\n", strings.Title(svc.Name)))
		if svc.Prefix != "" {
			buf.WriteString(fmt.Sprintf("\tg := r.Group(\"%s\")\n", svc.Prefix))
		} else {
			buf.WriteString("\tg := r.Group(\"\")\n")
		}
		buf.WriteString("\t{\n")

		for _, route := range svc.Routes {
			if route.Method != "" && route.Path != "" {
				buf.WriteString(fmt.Sprintf("\t\tg.%s(\"%s\", h.%s)\n", route.Method, route.Path, route.Handler))
			}
		}

		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	return generator.GenerateFileForce(
		filepath.Join(name, "internal", "web", "routes_gen.go"),
		buf.String(),
	)
}
