// Copyright 2025 ink-yht-code
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/ink-yht-code/gint-gen/generator"
	"github.com/ink-yht-code/gint-gen/parser"
	"github.com/spf13/cobra"
)

var apiCmd = &cobra.Command{
	Use:   "api <name>",
	Short: "从 .gint 文件生成 HTTP 代码",
	Long: `从 .gint 文件生成 types/handler/routes。

示例:
  gint-gen api user                  # 解析 user/user.gint
  gint-gen api user --file my.gint   # 指定文件`,
	Args: cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		name := args[0]
		file, _ := cmd.Flags().GetString("file")
		if file == "" {
			file = filepath.Join(name, name+".gint")
		}

		if err := genAPI(name, file); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("API code generated for '%s'.\n", name)
	},
}

func init() {
	rootCmd.AddCommand(apiCmd)
	apiCmd.Flags().StringP("file", "f", "", ".gint 文件路径")
}

func genAPI(name, file string) error {
	// 解析 .gint 文件
	p := parser.NewParser()
	api, err := p.ParseFile(file)
	if err != nil {
		return fmt.Errorf("parse .gint file: %w", err)
	}

	if err := api.Validate(); err != nil {
		return err
	}

	// 生成 types.go
	if err := genTypes(name, api); err != nil {
		return err
	}

	// 生成 handler.go
	if err := genHandler(name, api); err != nil {
		return err
	}

	// 生成 routes.go
	if err := genRoutes(name, api); err != nil {
		return err
	}

	return nil
}

func genTypes(name string, api *parser.API) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by gint-gen. DO NOT EDIT.\n")
	buf.WriteString("// source: " + name + ".gint\n\n")
	buf.WriteString("package types\n\n")

	for _, t := range api.Types {
		buf.WriteString(fmt.Sprintf("// %s %s\n", t.Name, t.Name))
		buf.WriteString(fmt.Sprintf("type %s struct {\n", t.Name))
		for _, f := range t.Fields {
			goType := parser.GoType(f.Type)
			if f.Tag != "" {
				buf.WriteString(fmt.Sprintf("\t%s %s `%s`\n", f.Name, goType, f.Tag))
			} else {
				buf.WriteString(fmt.Sprintf("\t%s %s\n", f.Name, goType))
			}
		}
		buf.WriteString("}\n\n")
	}

	return generator.GenerateFileForce(
		filepath.Join(name, "internal", "types", "types.go"),
		buf.String(),
	)
}

func genHandler(name string, api *parser.API) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by gint-gen. DO NOT EDIT.\n")
	buf.WriteString("// source: " + name + ".gint\n\n")
	buf.WriteString("package web\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"github.com/gin-gonic/gin\"\n")
	buf.WriteString("\t\"github.com/ink-yht-code/gint\"\n")
	buf.WriteString("\t\"github.com/ink-yht-code/gint/gctx\"\n")
	buf.WriteString("\t\"" + name + "/internal/server\"\n")
	buf.WriteString("\t\"" + name + "/internal/types\"\n")
	buf.WriteString(")\n\n")

	// Handler struct
	buf.WriteString("// Handler HTTP 处理器\n")
	buf.WriteString("// 实现 gint.Handler 接口\n")
	buf.WriteString("type Handler struct {\n")
	buf.WriteString("\tsvc *" + strings.Title(name) + "Service\n")
	buf.WriteString("}\n\n")

	// NewHandler
	buf.WriteString("// NewHandler 创建 Handler\n")
	buf.WriteString("func NewHandler(svc *" + strings.Title(name) + "Service) *Handler {\n")
	buf.WriteString("\treturn &Handler{svc: svc}\n")
	buf.WriteString("}\n\n")

	// PrivateRoutes
	buf.WriteString("// PrivateRoutes 注册需要认证的路由\n")
	buf.WriteString("func (h *Handler) PrivateRoutes(server *gin.Engine) {\n")
	buf.WriteString("\t// TODO: 添加需要认证的路由\n")
	buf.WriteString("\t// 示例: 使用 gint.S 或 gint.BS 包装器\n")
	buf.WriteString("\t// server.GET(\"/api/v1/profile\", gint.S(h.GetProfile))\n")
	buf.WriteString("}\n\n")

	// PublicRoutes
	buf.WriteString("// PublicRoutes 注册公开的路由\n")
	buf.WriteString("func (h *Handler) PublicRoutes(server *gin.Engine) {\n")
	for _, svc := range api.Services {
		for _, route := range svc.Routes {
			if route.Method != "" && route.Path != "" {
				// 判断使用 W 还是 B 包装器
				wrapper := "gint.W"
				if route.Request != "" {
					wrapper = "gint.B"
				}
				buf.WriteString(fmt.Sprintf("\tserver.%s(\"%s\", %s(h.%s))\n",
					route.Method, route.Path, wrapper, route.Handler))
			}
		}
	}
	buf.WriteString("}\n\n")

	// Handler methods
	for _, svc := range api.Services {
		for _, route := range svc.Routes {
			genHandlerMethod(&buf, route)
		}
	}

	// Health
	buf.WriteString("// Health 健康检查\n")
	buf.WriteString("func (h *Handler) Health(c *gin.Context) {\n")
	buf.WriteString("\tc.JSON(200, gin.H{\"status\": \"ok\"})\n")
	buf.WriteString("}\n")

	return generator.GenerateFileForce(
		filepath.Join(name, "internal", "web", "handler.go"),
		buf.String(),
	)
}

func genHandlerMethod(buf *strings.Builder, route parser.Route) {
	buf.WriteString("// " + route.Handler + " " + route.Handler + "\n")

	// 根据是否有 Request 决定签名
	if route.Request != "" {
		buf.WriteString(fmt.Sprintf("func (h *Handler) %s(ctx *gctx.Context, req *types.%s) (gint.Result, error) {\n",
			route.Handler, route.Request))
		buf.WriteString("\t// TODO: 实现业务逻辑\n")
		buf.WriteString("\t// 使用 gint.validator 进行参数校验\n")
		buf.WriteString("\t// vb := gint.NewValidatorBuilder()\n")
		buf.WriteString("\t// vb.Field(\"field\", req.Field).AddRule(gint.Required())\n")
		buf.WriteString("\t// vb.Validate()\n")
	} else {
		buf.WriteString(fmt.Sprintf("func (h *Handler) %s(ctx *gctx.Context) (gint.Result, error) {\n", route.Handler))
		buf.WriteString("\t// TODO: 实现业务逻辑\n")
	}

	// 返回响应
	if route.Response != "" {
		buf.WriteString(fmt.Sprintf("\treturn gint.Result{Code: 0, Data: &types.%s{}}, nil\n", route.Response))
	} else {
		buf.WriteString("\treturn gint.Result{Code: 0}, nil\n")
	}
	buf.WriteString("}\n\n")
}

func genRoutes(name string, api *parser.API) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by gint-gen. DO NOT EDIT.\n")
	buf.WriteString("// source: " + name + ".gint\n\n")
	buf.WriteString("package web\n\n")
	buf.WriteString("import \"github.com/gin-gonic/gin\"\n\n")

	for _, svc := range api.Services {
		buf.WriteString(fmt.Sprintf("// Register%sRoutes 注册 %s 服务路由\n", strings.Title(svc.Name), svc.Name))
		buf.WriteString(fmt.Sprintf("func Register%sRoutes(r *gin.Engine, h *Handler) {\n", strings.Title(svc.Name)))
		if svc.Prefix != "" {
			buf.WriteString(fmt.Sprintf("\tg := r.Group(\"%s\")\n", svc.Prefix))
		} else {
			buf.WriteString("\tg := r.Group(\"\")\n")
		}
		buf.WriteString("\t{\n")

		for _, route := range svc.Routes {
			if route.Method != "" && route.Path != "" {
				buf.WriteString(fmt.Sprintf("\t\tg.%s(\"%s\", h.%s)\n", route.Method, route.Path, route.Handler))
			}
		}

		buf.WriteString("\t}\n")
		buf.WriteString("}\n\n")
	}

	return generator.GenerateFileForce(
		filepath.Join(name, "internal", "web", "routes.go"),
		buf.String(),
	)
}
