// Copyright 2025 ink-yht-code
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"

	"github.com/ink-yht-code/gint/gint-gen/generator"
	"github.com/spf13/cobra"
)

var repoCmd = &cobra.Command{
	Use:   "repo <name>",
	Short: "从 SQL DDL 生成 repository 代码",
	Long: `从 SQL DDL 文件生成 repository 代码。

示例:
  gint-gen repo user --ddl schema.sql
  gint-gen repo user --ddl schema.sql --table users`,
	Args: cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		name := args[0]
		ddlFile, _ := cmd.Flags().GetString("ddl")
		table, _ := cmd.Flags().GetString("table")

		if ddlFile == "" {
			fmt.Fprintln(os.Stderr, "Error: --ddl is required")
			os.Exit(1)
		}

		if err := genRepo(name, ddlFile, table); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("Repository code generated for '%s'.\n", name)
	},
}

func init() {
	rootCmd.AddCommand(repoCmd)
	repoCmd.Flags().String("ddl", "", "SQL DDL 文件路径")
	repoCmd.Flags().String("table", "", "表名（默认使用服务名）")
}

// TableInfo 表信息
type TableInfo struct {
	Name    string
	Columns []ColumnInfo
}

// ColumnInfo 列信息
type ColumnInfo struct {
	Name     string
	Type     string
	Nullable bool
}

func genRepo(name, ddlFile, table string) error {
	// 默认表名
	if table == "" {
		table = name + "s"
	}

	// 解析 DDL
	tableInfo, err := parseDDL(ddlFile, table)
	if err != nil {
		return err
	}

	// 生成 DAO model
	if err := genDAOModel(name, tableInfo); err != nil {
		return err
	}

	// 生成 DAO 实现
	if err := genDAORepo(name, tableInfo); err != nil {
		return err
	}

	// 生成 repository 接口
	if err := genRepoInterface(name, tableInfo); err != nil {
		return err
	}

	return nil
}

func parseDDL(ddlFile, tableName string) (*TableInfo, error) {
	data, err := os.ReadFile(ddlFile)
	if err != nil {
		return nil, err
	}

	content := string(data)
	info := &TableInfo{Name: tableName, Columns: make([]ColumnInfo, 0)}

	// 查找 CREATE TABLE 语句
	re := regexp.MustCompile(`(?i)CREATE\s+TABLE\s+` + "`?" + tableName + "`?" + `\s*\(([^;]+)\)`)
	matches := re.FindStringSubmatch(content)
	if len(matches) < 2 {
		return nil, fmt.Errorf("table %s not found in DDL", tableName)
	}

	// 解析列
	columnsStr := matches[1]
	scanner := bufio.NewScanner(strings.NewReader(columnsStr))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "PRIMARY") || strings.HasPrefix(line, "KEY") || strings.HasPrefix(line, "INDEX") || strings.HasPrefix(line, "UNIQUE") {
			continue
		}

		// 解析列定义
		colRe := regexp.MustCompile(`^(\w+)\s+(\w+)(?:\([^)]+\))?(?:\s+(NOT\s+NULL|NULL))?`)
		colMatches := colRe.FindStringSubmatch(line)
		if len(colMatches) >= 3 {
			col := ColumnInfo{
				Name: colMatches[1],
				Type: colMatches[2],
			}
			if len(colMatches) > 3 {
				col.Nullable = !strings.EqualFold(colMatches[3], "NOT NULL")
			}
			info.Columns = append(info.Columns, col)
		}
	}

	return info, nil
}

func genDAOModel(name string, table *TableInfo) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by gint-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package dao\n\n")
	buf.WriteString("import \"time\"\n\n")
	buf.WriteString(fmt.Sprintf("// %s %s 表模型\n", strings.Title(name), table.Name))
	buf.WriteString(fmt.Sprintf("type %s struct {\n", strings.Title(name)))
	for _, col := range table.Columns {
		goType := sqlTypeToGo(col.Type, col.Nullable)
		fieldName := toCamelCase(col.Name)
		buf.WriteString(fmt.Sprintf("\t%s %s `gorm:\"column:%s\"`\n", fieldName, goType, col.Name))
	}
	buf.WriteString("}\n\n")
	buf.WriteString(fmt.Sprintf("// TableName 表名\n"))
	buf.WriteString(fmt.Sprintf("func (%s) TableName() string {\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\treturn \"%s\"\n", table.Name))
	buf.WriteString("}\n")

	return generator.GenerateFileForce(
		filepath.Join(name, "internal", "repository", "dao", "model.go"),
		buf.String(),
	)
}

func genDAORepo(name string, table *TableInfo) error {
	var buf strings.Builder
	buf.WriteString("// Code generated by gint-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package dao\n\n")
	buf.WriteString("import (\n")
	buf.WriteString("\t\"context\"\n")
	buf.WriteString("\t\"gorm.io/gorm\"\n")
	buf.WriteString(")\n\n")
	buf.WriteString(fmt.Sprintf("// %sDAO %s 数据访问对象\n", strings.Title(name), name))
	buf.WriteString(fmt.Sprintf("type %sDAO struct {\n", strings.Title(name)))
	buf.WriteString("\tdb *gorm.DB\n")
	buf.WriteString("}\n\n")
	buf.WriteString(fmt.Sprintf("// New%sDAO 创建 DAO\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("func New%sDAO(db *gorm.DB) *%sDAO {\n", strings.Title(name), strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\treturn &%sDAO{db: db}\n", strings.Title(name)))
	buf.WriteString("}\n\n")
	buf.WriteString("// Create 创建记录\n")
	buf.WriteString(fmt.Sprintf("func (d *%sDAO) Create(ctx context.Context, m *%s) error {\n", strings.Title(name), strings.Title(name)))
	buf.WriteString("\treturn d.db.WithContext(ctx).Create(m).Error\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// GetByID 根据 ID 获取\n")
	buf.WriteString(fmt.Sprintf("func (d *%sDAO) GetByID(ctx context.Context, id int64) (*%s, error) {\n", strings.Title(name), strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\tvar m %s\n", strings.Title(name)))
	buf.WriteString("\terr := d.db.WithContext(ctx).Where(\"id = ?\", id).First(&m).Error\n")
	buf.WriteString("\treturn &m, err\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Update 更新记录\n")
	buf.WriteString(fmt.Sprintf("func (d *%sDAO) Update(ctx context.Context, m *%s) error {\n", strings.Title(name), strings.Title(name)))
	buf.WriteString("\treturn d.db.WithContext(ctx).Save(m).Error\n")
	buf.WriteString("}\n\n")
	buf.WriteString("// Delete 删除记录\n")
	buf.WriteString(fmt.Sprintf("func (d *%sDAO) Delete(ctx context.Context, id int64) error {\n", strings.Title(name)))
	buf.WriteString("\treturn d.db.WithContext(ctx).Delete(&" + strings.Title(name) + "{}, id).Error\n")
	buf.WriteString("}\n")

	return generator.GenerateFileForce(
		filepath.Join(name, "internal", "repository", "dao", "repo.go"),
		buf.String(),
	)
}

func genRepoInterface(name string, table *TableInfo) error {
	var buf strings.Builder
	buf.WriteString("package port\n\n")
	buf.WriteString("import \"context\"\n\n")
	buf.WriteString(fmt.Sprintf("// %sRepository %s 仓库接口\n", strings.Title(name), name))
	buf.WriteString(fmt.Sprintf("type %sRepository interface {\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\tCreate(ctx context.Context, entity *%s) error\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\tGetByID(ctx context.Context, id int64) (*%s, error)\n", strings.Title(name)))
	buf.WriteString(fmt.Sprintf("\tUpdate(ctx context.Context, entity *%s) error\n", strings.Title(name)))
	buf.WriteString("\tDelete(ctx context.Context, id int64) error\n")
	buf.WriteString("}\n")

	return generator.GenerateFile(
		filepath.Join(name, "internal", "domain", "port", strings.ToLower(name)+"_repo.go"),
		buf.String(),
	)
}

func sqlTypeToGo(sqlType string, nullable bool) string {
	sqlType = strings.ToUpper(sqlType)
	var goType string

	switch {
	case strings.Contains(sqlType, "INT"):
		if strings.Contains(sqlType, "BIGINT") {
			goType = "int64"
		} else if strings.Contains(sqlType, "SMALLINT") || strings.Contains(sqlType, "TINYINT") {
			goType = "int8"
		} else {
			goType = "int"
		}
	case strings.Contains(sqlType, "VARCHAR") || strings.Contains(sqlType, "TEXT") || strings.Contains(sqlType, "CHAR"):
		goType = "string"
	case strings.Contains(sqlType, "BOOL"):
		goType = "bool"
	case strings.Contains(sqlType, "FLOAT") || strings.Contains(sqlType, "DOUBLE"):
		goType = "float64"
	case strings.Contains(sqlType, "DECIMAL"):
		goType = "float64"
	case strings.Contains(sqlType, "DATE") || strings.Contains(sqlType, "TIME"):
		goType = "time.Time"
	case strings.Contains(sqlType, "JSON"):
		goType = "string"
	default:
		goType = "string"
	}

	if nullable {
		return "*" + goType
	}
	return goType
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "_")
	for i, p := range parts {
		if len(p) > 0 {
			parts[i] = strings.ToUpper(p[:1]) + p[1:]
		}
	}
	return strings.Join(parts, "")
}
