// Copyright 2025 ink-yht-code
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

package cmd

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	"github.com/ink-yht-code/gint/gint-gen/generator"
	"github.com/spf13/cobra"
)

var rpcCmd = &cobra.Command{
	Use:   "rpc <name>",
	Short: "从 .proto 文件生成 gRPC 代码",
	Long: `从 .proto 文件生成 gRPC 代码。

需要安装:
  - protoc
  - protoc-gen-go
  - protoc-gen-go-grpc

示例:
  gint-gen rpc user                  # 解析 user/user.proto
  gint-gen rpc user --file my.proto  # 指定文件`,
	Args: cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		name := args[0]
		file, _ := cmd.Flags().GetString("file")
		if file == "" {
			file = filepath.Join(name, name+".proto")
		}

		if err := genRPC(name, file); err != nil {
			fmt.Fprintf(os.Stderr, "Error: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("RPC code generated for '%s'.\n", name)
	},
}

func init() {
	rootCmd.AddCommand(rpcCmd)
	rpcCmd.Flags().StringP("file", "f", "", ".proto 文件路径")
}

func genRPC(name, file string) error {
	// 检查 protoc 是否安装
	if _, err := exec.LookPath("protoc"); err != nil {
		return fmt.Errorf("protoc not found, please install it first")
	}

	// 获取绝对路径
	absFile, err := filepath.Abs(file)
	if err != nil {
		return err
	}

	protoDir := filepath.Dir(absFile)
	protoName := filepath.Base(absFile)

	// 生成 gRPC 代码
	// protoc --go_out=. --go_opt=paths=source_relative \
	//        --go-grpc_out=. --go-grpc_opt=paths=source_relative \
	//        user.proto
	args := []string{
		"--go_out=.",
		"--go_opt=paths=source_relative",
		"--go-grpc_out=.",
		"--go-grpc_opt=paths=source_relative",
		protoName,
	}

	if verbose {
		fmt.Printf("Running: protoc %s\n", strings.Join(args, " "))
	}

	cmd := exec.Command("protoc", args...)
	cmd.Dir = protoDir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("protoc failed: %w", err)
	}

	// 生成 server wrapper
	if err := genRPCServer(name); err != nil {
		return err
	}

	return nil
}

func genRPCServer(name string) error {
	serverCode := fmt.Sprintf(`// Code generated by gint-gen. DO NOT EDIT.

package web

import (
	"context"

	"google.golang.org/grpc"
	"%s/internal/server"
)

// RPCServer gRPC 服务包装器
type RPCServer struct {
	Unimplemented%sServer
	svc *server.%sService
}

// NewRPCServer 创建 RPC Server
func NewRPCServer(svc *server.%sService) *RPCServer {
	return &RPCServer{svc: svc}
}

// Register 注册到 gRPC Server
func (s *RPCServer) Register(server grpc.ServiceRegistrar) {
	Register%sServer(server, s)
}
`, name, strings.Title(name), strings.Title(name), strings.Title(name), strings.Title(name))

	return generator.GenerateFileForce(
		filepath.Join(name, "internal", "web", "rpc.go"),
		serverCode,
	)
}
